import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import * as anchor from "@coral-xyz/anchor";
import { logger } from "./logger";

const PROGRAM_ID = new PublicKey(process.env.PROGRAM_ID!);
const RPC_URL = process.env.HELIUS_RPC_URL!;

export async function updateSiteUrlOnChain(
  walletAddress: string,
  arweaveUrl: string
): Promise<void> {
  if (arweaveUrl.length > 64) {
    // Irys URL format: https://arweave.net/<43-char-id> = ~67 chars
    // Store only the transaction ID (43 chars) — reconstruct URL on frontend
    arweaveUrl = arweaveUrl.replace("https://arweave.net/", "");
  }

  // Convert URL to [u8; 64]
  const urlBytes = new Uint8Array(64);
  const encoded = new TextEncoder().encode(arweaveUrl.slice(0, 64));
  urlBytes.set(encoded);

  const backendKeypair = Keypair.fromSecretKey(
    Buffer.from(process.env.BACKEND_PRIVATE_KEY!, "base64")
  );

  const connection = new Connection(RPC_URL, "confirmed");
  const wallet = new anchor.Wallet(backendKeypair);
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });

  // IDL is loaded from the file generated by anchor build
  const idl = require("../../idl/code_eternal_router.json");
  const program = new anchor.Program(idl, PROGRAM_ID, provider);

  const userWallet = new PublicKey(walletAddress);
  const [userStatePda] = PublicKey.findProgramAddressSync(
    [Buffer.from("user"), userWallet.toBuffer()],
    PROGRAM_ID
  );

  await (program.methods as any)
    .updateSiteUrl(Array.from(urlBytes), 1) // status=1 (ready)
    .accounts({
      backendAuthority: backendKeypair.publicKey,
      userState: userStatePda,
      userWallet: userWallet,
    })
    .rpc();

  logger.info(`On-chain URL updated for ${walletAddress}: ${arweaveUrl}`);
}
